### ISSUE TITLE
return results in the original transcription / form

### ISSUE THREAD

**Issue by eroux** [buda-base/autocomplete-prototype#11]
As seen in the recording in https://github.com/buda-base/autocomplete-prototype/issues/10 when doing the autocomplete in Tibetan Unicode, the results come in Wylie. I think it makes more sense that the API to return results in Unicode in that case,  instead of the frontend trying to interpret the results from the API. Would that be ok @roopeux

**Comment by roopeux** [comment]
Fix pushed, but I will check highlight later.

**Comment by eroux** [comment]
done
