### ISSUE TITLE
suggested query returning 500 / too_many_nested_clauses

### ISSUE THREAD

**Issue by berger-n** [buda-base/autocomplete-prototype#12]
this query triggered by a suggestion from autocomplete returns 500: 
https://library-dev.bdrc.io/osearch/associated/PR1PL480/search?q=things%20to%20come%20and%20accounts%20of%20padma%20bkod 

here is the corresponding [curl](https://github.com/user-attachments/files/16363304/curl.txt) and response from the server:

```json
{
 "responses": [
    {
      "error": {
        "caused_by": {
          "caused_by": {
            "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
            "type": "too_many_nested_clauses"
          },
          "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
          "type": "too_many_nested_clauses"
        },
        "failed_shards": [
          {
            "index": "bdrc_prod",
            "node": "l7DVO7FRSwe6xVSLYSeKyA",
            "reason": {
              "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
              "type": "too_many_nested_clauses"
            },
            "shard": 0
          }
        ],
        "grouped": true,
        "phase": "query",
        "reason": "all shards failed",
        "root_cause": [
          {
            "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
            "type": "too_many_nested_clauses"
          }
        ],
        "type": "search_phase_execution_exception"
      },
      "status": 500
    }
  ],
  "took": 13
}
```

**Comment by roopeux** [comment]
This is a common error with massive jsons.  I will have to fix the actual issue, but the weird thing is that on my local this query works and my local `search_bdrc.py` looks the same as in the repo.  @eroux is it possible that the last version is not deployed?

**Comment by roopeux** [comment]
I reduced the quality of two-phrase search a bit more as a temporary solution.  When we add languages and the jsons actually explode, I will run parallel queries or find other means to stay within limits.

**Comment by eroux** [comment]
seems to work now! let's close

**Comment by berger-n** [comment]
thanks a lot! 
just stumbled upon a case where it's still happening though: 
https://library-dev.bdrc.io/osearch/search?q=Spyod%20%27jug%20gi%20%27grel%20b%C5%9Bad%20rgyal%20sras%20yon%20tan%20bum%20bza%E1%B9%85%20%2FThub-bstan-chos-kyi-grags-pa.

![simplescreenrecorder-2024-07-26_12 13 23 mkv](https://github.com/user-attachments/assets/378eabd5-837b-4301-86aa-12f9191f117c)


```json
[
    {
        "error": {
            "caused_by": {
                "caused_by": {
                    "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
                    "type": "too_many_nested_clauses"
                },
                "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
                "type": "too_many_nested_clauses"
            },
            "failed_shards": [
                {
                    "index": "bdrc_prod",
                    "node": "l7DVO7FRSwe6xVSLYSeKyA",
                    "reason": {
                        "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
                        "type": "too_many_nested_clauses"
                    },
                    "shard": 0
                }
            ],
            "grouped": true,
            "phase": "query",
            "reason": "all shards failed",
            "root_cause": [
                {
                    "reason": "Query contains too many nested clauses; maxClauseCount is set to 1024",
                    "type": "too_many_nested_clauses"
                }
            ],
            "type": "search_phase_execution_exception"
        },
        "status": 500
    }
]
```

**Comment by roopeux** [comment]
@berger-n, it is good to know that it still breaks but we should probably fix this later when we have a full picture of all languages and etexts to search.

**Comment by eroux** [comment]
@roopeux this still seems to be present with some searches (including the very common "pha rol tu phyin pa stong phrag brgya pa"):

```
curl 'https://autocomplete.bdrc.io/msearch' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0' -H 'Accept: */*' -H 'Accept-Language: fr-FR,en;q=0.7,en-US;q=0.3' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Content-Type: application/json' -H 'Referer: https://library-dev.bdrc.io/' -H 'Origin: https://library-dev.bdrc.io' -H 'DNT: 1' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Authorization: Basic cHVibGljcXVlcnk6MFZzZzFRdmpMa1RDenZ0bA==' -H 'Connection: keep-alive' -H 'Priority: u=4' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data-raw $'{"index":"bdrc_prod"}\n{"from":0,"size":20,"aggs":{"associatedCentury":{"terms":{"field":"associatedCentury","size":20}},"associatedTradition":{"terms":{"field":"associatedTradition","size":20}},"author":{"terms":{"field":"author","size":20}},"etext_access":{"terms":{"field":"etext_access","size":20}},"etext_quality":{"range":{"field":"etext_quality","ranges":[{"from":0,"to":0.8},{"from":0.8,"to":0.95},{"from":0.95,"to":1.01},{"from":1.99,"to":2.01},{"from":2.99,"to":3.01},{"from":3.99,"to":4.01}]}},"etext_search":{"terms":{"field":"etext_search","size":20}},"inCollection":{"terms":{"field":"inCollection","size":20}},"language":{"terms":{"field":"language","size":20}},"personGender":{"terms":{"field":"personGender","size":20}},"placeType":{"terms":{"field":"placeType","size":20}},"printMethod":{"terms":{"field":"printMethod","size":20}},"scans_access":{"terms":{"field":"scans_access","size":20}},"script":{"terms":{"field":"script","size":20}},"translator":{"terms":{"field":"translator","size":20}},"type":{"terms":{"field":"type","size":20}},"workGenre":{"terms":{"field":"workGenre","size":20}},"workIsAbout":{"terms":{"field":"workIsAbout","size":20}}},"highlight":{"fields":{"associated_res":{},"graphs":{},"other_id":{},"inRootInstance":{},"type":{},"inCollection":{},"associatedTradition":{},"personGender":{},"hasSourcePrintery":{},"printMethod":{},"script":{},"language":{},"partOf":{},"partType":{},"issueName":{},"workGenre":{},"workIsAbout":{},"author":{},"translator":{},"seriesName_res":{},"seriesName_bo_x_ewts":{},"seriesName_en":{},"summary_bo_x_ewts":{},"summary_en":{},"authorshipStatement_bo_x_ewts":{},"authorshipStatement_en":{},"publisherName_bo_x_ewts":{},"publisherLocation_bo_x_ewts":{},"publisherName_en":{},"publisherLocation_en":{},"prefLabel_bo_x_ewts":{"fragment_size":500},"prefLabel_en":{"fragment_size":500},"comment_bo_x_ewts":{},"comment_en":{},"altLabel_bo_x_ewts":{"fragment_size":500},"altLabel_en":{"fragment_size":500}}},"query":{"function_score":{"script_score":{"script":{"id":"bdrc-score"}},"query":{"bool":{"filter":[],"must":[{"multi_match":{"type":"phrase","query":"pha rol tu phyin pa stong phrag brgya pa","fields":["seriesName_bo_x_ewts^0.1","seriesName_en^0.1","authorshipStatement_bo_x_ewts^0.005","authorshipStatement_en^0.005","publisherName_bo_x_ewts^0.01","publisherLocation_bo_x_ewts^0.01","publisherName_en^0.01","publisherLocation_en^0.01","prefLabel_bo_x_ewts^1","prefLabel_en^1","comment_bo_x_ewts^0.0001","comment_en^0.0001","altLabel_bo_x_ewts^0.6","altLabel_en^0.6"]}}]}}}}}\n'
```

reported from https://github.com/buda-base/public-digital-library/issues/918#issuecomment-2354911278

**Comment by roopeux** [comment]
Fix pushed

**Comment by berger-n** [comment]
thank you very much! both work now: 
- https://library-dev.bdrc.io/osearch/search?q=pha%20rol%20tu%20phyin%20pa%20stong%20phrag%20brgya%20pa
  
  ![image](https://github.com/user-attachments/assets/6c255768-0994-47b4-91ad-320c9f2003fb)

 
- https://library-dev.bdrc.io/osearch/associated/PR1PL480/search?q=things%20to%20come%20and%20accounts%20of%20padma%20bkod
  
  ![image](https://github.com/user-attachments/assets/7ce6aa5e-2a7f-4660-90d0-add0194bbe28)

**Comment by berger-n** [comment]
this one does not:
https://library-dev.bdrc.io/osearch/search?q=Spyod%20%27jug%20gi%20%27grel%20b%C5%9Bad%20rgyal%20sras%20yon%20tan%20bum%20bza%E1%B9%85%20%2FThub-bstan-chos-kyi-grags-pa

**Comment by berger-n** [comment]
neither does this other autosuggestion: 
https://library-dev.bdrc.io/osearch/search?q=spyod%20%27grel%20pa%20sangs%20rgyas%20rjes%20dran%20byams%20smon%20%27grel%20pa%20sher

**Comment by berger-n** [comment]
(just keeping it open as it seems to be happening again here:
- https://library-dev.bdrc.io/osearch/search?q=spyod%20%27grel%20pa%20sangs%20rgyas%20rjes%20dran%20byams%20smon%20%27grel%20pa%20sher
  
  ![image](https://github.com/user-attachments/assets/94b6ca88-e349-4a1c-a933-b13db8809ac5)

- https://library-dev.bdrc.io/osearch/search?q=sems%20dpa%27i%20spyod%20pa%20la%20%27jug%20pa%27i%20tshig%20%27grel%20%27jam%20dbyangs%20bla
 
 ![image](https://github.com/user-attachments/assets/bbd33496-df57-428e-8835-8f0412eca801)

)

**Comment by roopeux** [comment]
@eroux (as said in Discord) would it be possible to increase the max clauses a bit from 1024, and see if it Opensearch starts bugging?  I would not loosen the parameters but we would get rid of these errors.  The reason I would not want to tighten the parameters anymore is that I am already seeing actual degradation of search UX.

**Comment by eroux** [comment]
Can you give me a link to the doc so I can try that?

**Comment by roopeux** [comment]
Check `max_clause_count` at https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index-settings/#dynamic-index-level-index-settings

The setting is dynamic, this GPT query might work directly
```
PUT _cluster/settings
{
  "persistent": {
    "indices.query.bool.max_clause_count": 1500
  }
}
```

**Comment by roopeux** [comment]
The queries of @berger-n above also work now.  The problem should not immediately come back because we added almost 50% of clauses.

The number of fields seems to affect so little that I am not even taking that into account.  The number of tokens and the number of subqueries are the factors, which can cause the error. The number of tokens we cannot control, but I am limiting the subqueries.

**Comment by eroux** [comment]
ok, closing then, we can reopen if necessary

**Comment by berger-n** [comment]
perfect! thanks a lot
