### ISSUE TITLE
Etext only search

### ISSUE THREAD

**Issue by roopeux** [buda-base/autocomplete-prototype#15]
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/b5ad177a-be02-4266-8f32-a186841b1863">

**Comment by berger-n** [comment]
done regarding the UI: [link](https://library-dev.bdrc.io/osearch/search?q=%E0%BD%96%E0%BE%B1%E0%BC%8B%E0%BD%84%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BC%8B%E0%BD%A6%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%96%E0%BD%BC%E0%BC%8B%E0%BD%98%E0%BD%9A%E0%BD%BC&etext_search%5B0%5D=true)

![simplescreenrecorder-2024-07-30_10 52 41 mkv](https://github.com/user-attachments/assets/6e811b78-40da-4ea9-89ee-ab9ec99ed8b4)
