### ISSUE TITLE
query on date

### ISSUE THREAD

**Issue by eroux** [buda-base/autocomplete-prototype#16]
it's sometimes quite useful to search on dates (particularly for persons), if users type a date with 4 digits we should have a special path like we do for IDs. That special path would search in the fields publicationDate, birthEvent and deathEvent (which I realize are not there yet)

**Comment by eroux** [comment]
still not satisfactory. I use it all the time to identify persons, see for instance the difference between

https://library-dev.bdrc.io/osearch/search?q=1975&type%5B0%5D=Person

https://library.bdrc.io/search?date=%221975%22&t=Person

although I suppose it's not too bad as it's still an option in the advanced search:

https://library-dev.bdrc.io/search?date=%221975%22&t=Person

**Comment by roopeux** [comment]
It would find year ranges right?  greater than birth year, less than death year, etc?

**Comment by eroux** [comment]
Not necessarily no, it can just be a basic keyword match on the date related fields

**Comment by roopeux** [comment]
I pushed a version that matches `birthDate`, `deathDate`, `publicationDate` if exact.  Can be multiple. It also matches century when typed with two zeroes like 1800.  In the 1% cases when century overlaps with birth/death, the latter is strongly boosted.

Year match does not work with AND or quotes.

**Comment by eroux** [comment]
Wonderful, thanks!

**Comment by roopeux** [comment]
Forgot to say that years can be combined with keywords, like "khyentse 1800"
