### ISSUE TITLE
Autosuggest in Vespa

### ISSUE THREAD

**Issue by roopeux** [buda-base/autocomplete-prototype#6]
Create autosuggest in Vespa in order to combine prefix search with fuzzy match.

Improvements over the current version
- match inside titles, not only beginning (this will fix several know UX cases)
- match any length, not only 20 chars
- allow scoped suggestions, like texts of a collection or works by or about a person (this would work in ES as well.  Crucial in the new prototyped UX)

FYI @eroux

**Comment by eroux** [comment]
Ok! One thing I'm not to excited about is introducong a new database to the list of things to maintain but... let's see

**Comment by roopeux** [comment]
The benefit of using Vespa is not big enough.  Ditching this idea.
