### ISSUE TITLE
handle AND in text query

### ISSUE THREAD

**Issue by eroux** [buda-base/autocomplete-prototype#7]
On the current website when there is an AND, the query is interpreted as two (or well, multiple) phrases separated by " AND ". This is particularly useful for etexts. There might be better ways for users to indicate that but since it already exists let's handle it

**Comment by roopeux** [comment]
@eroux, our current search does AND by default.

**Comment by eroux** [comment]
We don't do it in the etexts (which is a big use case for the AND)

if users type "AND" in the query it will mess it up in the current system

We don't provide control over where to cut the phrase, or multiple AND

We don't provide AND for long queries

So no

**Comment by roopeux** [comment]
In etexts we currently require exact phrase which is AND by default.

Users practically never type AND.  According to our logs, roughly ten times in a million, probably including ourselves testing.  I can spend time taking care of this 0.001% of use cases if you want.

**Comment by eroux** [comment]
the usage of AND on the production website is the following:

if the user types "gsung 'bum AND mi pham" (I know, this example works on the dev website, that's not the point) it will select results with a match phrase for "gsung 'bum" and a match phrase on "mi pham", see https://www.bdrc.io/blog/2021/03/03/search-me/ 

We can imagine having that as a low priority, but let's not give up on it no

**Comment by eroux** [comment]
we could imagine having an additional syntax with double quotes, like `"gsung 'bum" "mi pham"`, that's also fine
