### ISSUE TITLE
scoped autocomplete

### ISSUE THREAD

**Issue by eroux** [buda-base/autocomplete-prototype#8]
see https://github.com/buda-base/public-digital-library/issues/897#issuecomment-2243309809 I'm not sure how you want to achieve that Roope, but there are basically two cases:

- the general case is when searching for records associated with a record, on the record page, this is what's described in the comment, and the scope should be driven by the `associated_res` property in the database
- the other case is searching in outlines, in that case the scope is a certain value of the `inRootInstance` property in the database

**Comment by roopeux** [comment]
@berger-n @eroux , both autosuggest and search support scope but autosuggest has not been documented or discussed yet.

I suggest we change the autosuggest API input to `{"query": "snyen ngag chen p", "scope": ["P1","MW1234"] }`
`scope` should be `all`when it is not limited.

Regarding search, is it possible to send the query with certain filters which define the scope (in addition to possible user-defined filters)?

**Comment by eroux** [comment]
Ah thanks! @berger-n can you add that to the query you send? For regular search it's already implemented I think

**Comment by eroux** [comment]
(you can use the same "scope" for both outlines and associated search for the autocomplete)

**Comment by berger-n** [comment]
thanks a lot! done: 
- https://library-dev.bdrc.io/show/bdr:T30
  
  ![simplescreenrecorder-2024-07-24_14 07 25 mkv](https://github.com/user-attachments/assets/cbc7b74c-502a-489e-b18b-8665f1ccf3c3)
---
 
- https://library-dev.bdrc.io/show/bdr:MW21807
   
  ![simplescreenrecorder-2024-07-24_14 08 26 mkv](https://github.com/user-attachments/assets/75f87128-e057-451e-a9db-8d3b6a5d5357)

  (note that there's seems to be an issue with the old query, not always returning all the data needed though what's returned by the autocomplete query is ok, for example: https://ldspdi.bdrc.io/query/graph/Outline_search?LG_NAME=en&R_RES=bdr%3AMW21807&L_NAME=%22and%20other%20visionary%20poetry%20of%20%27jam%20dbyangs%20mkhyen%22 where some nodes are lost on the way to https://library-dev.bdrc.io/show/bdr:MW21807_427686?s=q%3Dvisionary%2520poetry%2520of%2520%2527jam%2520dbyangs%2520mkhyen)
