### ISSUE TITLE
"hallucinations" in the auto complete

### ISSUE THREAD

**Issue by eroux** [buda-base/autocomplete-prototype#9]
when searching snyen ngag (poetry), the autocomplete suggests "snyan ngag chen mo" ("great poetry"), which doesn't even really exist as a concept, and doesn't seem to be appearing anywhere in the titles or names... @roopeux let's investigate where this comes from and fix the indexing

<img width="393" alt="Screenshot 2024-07-21 at 9 43 16 AM" src="https://github.com/user-attachments/assets/56a6d067-90fd-496a-b902-aa732f26bff8">

**Comment by roopeux** [comment]
The string is in one of the altLabels of MW4CZ45309 (re: Discord)

**Comment by eroux** [comment]
ah ok I see, sorry, I was wrong in my transliteration. I think what was confusing is that the first result with "snyan ngag chen po" in a title is number 10, the previous ones are results that contain `snyan ngag` and `chen po` but not very close apart.

@JannTibetan any thoughts?

**Comment by JannTibetan** [comment]
I was just going to try this again but it seems that this issue has already been resolved. 
My apologies if it I made a big deal about a small issue but perhaps it had a broader application than just this one case.
